flowchart TD
    A[Bronze] --> B[Silver]
    B --> C[Gold]
    C --> D[Indicador Município]
    C --> E[Indicador UF]
    C --> F[Comparativo Meta x Resultado]
    C --> G[Ranking Prioritário]
    C --> H[Base IA]
